### ISSUE TITLE
Extensions.cs is mssing from the project

### ISSUE THREAD

**Issue by shiitake** [schgab/RadioTerm#1]
When trying to build the project in VS 2019 I get the build error `Source file 'C:\git\RadioTerm\RadioTerm\Extensions.cs' could not be found.`

It is referenced in project file but isn't included in the repo.

**Comment by MaheuTaroo** [comment]
I second this. Has it been removed for good, or is it unintentional?

**Comment by MaheuTaroo** [comment]
I second this. Has it been removed for good, or is it unintentional? @schgab

**Comment by schgab** [comment]
I just forgot to git add it ^^

**Comment by schgab** [comment]
Fixed
