### ISSUE TITLE
Playing station from URL throws System.Runtime.InteropServices.COMException with HRESULT 0xC00D36C4

### ISSUE THREAD

**Issue by MaheuTaroo** [schgab/RadioTerm#3]
When adding a station and pressing the "Next" option, the error in the title appears. It also happens when application starts and I have saved stations.

Files showing error: [error.zip](https://github.com/schgab/RadioTerm/files/4969800/error.zip)

@schgab pls fix...? This seems like an interesting concept to have as an application

**Comment by schgab** [comment]
Added playability check
