### ISSUE TITLE
Error while building: "A numeric comparison was attempted on "$(MsBuildMajorVersion)" that evaluates to "" instead of a number, in condition "($(MsBuildMajorVersion) < 16)"."

### ISSUE THREAD

**Issue by MaheuTaroo** [schgab/RadioTerm#6]

**Comment by schgab** [comment]
this is an issue with visual studio. [stackoverflow](https://stackoverflow.com/questions/57261146/a-numeric-comparison-was-attmepted-on-msbuildversion-that-evaluates-to-i) simply restarting vs is the solution at least for me

Edit: You just need to clean the solution first, idk why. Added that to the readme
